swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transactions:
    get:
      security:
        - Bearer: []
      tags: 
        - Transactions
      summary: Retourne toutes les transactions du mois en cours, par compte
      description: Retourne toutes les transactions du mois en cours, par compte
      parameters:
        - name: Authorization
          type: string
          in: header
          description: Attach Bearer JWT token - Permet de s'assurer que le client détient les droits nécessaires
          required: true
      responses:
        '200' :
          description: Succès
          schema: 
            $ref: '#/definitions/ManyGetSuccessResponse'
        '401':
          description: Utilisateur non authorisé
  /transactions/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Retourne une transaction détaillée
      description: Retourne une transaction détaillée
      parameters:
        - name: Authorization
          type: string
          in: header
          description: Attach Bearer JWT token - Permet de s'assurer que le client détient les droits nécessaires
          required: true
        - name: id
          in: path
          type: integer
          required: true
      responses:
        '200' :
          description: Succès
          schema:
            $ref: '#/definitions/SingleSuccessResponse'
        '401':
          description: Utilisateur non authorisé
    put:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Modifie les détails d'une transaction
      description: Modifie les détails d'une transaction
      parameters:
        - name: Authorization
          in: header
          type: string
          description: Attach Bearer JWT token - Permet de s'assurer que le client détient les droits nécessaires
          required: true
        - name: id
          in: path
          type: integer
          required: true
        - name: body
          in: body
          description: Met à jour une transaction d'épargne, les propriétés renseignées seront mises à jour
          required: true
          schema:
            $ref: '#/definitions/UpdateTransaction'
      produces:
        - application/json
      responses:
        '200':
          description: Requête réussie
          schema:
            $ref: '#/definitions/SingleSuccessResponse'
        '401':
          description: Utilisateur non authorisé
        '404':
          description: Id de transaction invalide
      
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  SingleSuccessResponse:
    type: object
    properties:
      id:
        type: string
      date:
        type: string
      description:
        type: string
      amount:
        type: number
      balance: 
        type: number
      category:
        type: string
      notes: 
        type: string
      accountId:
        type: string
  ManyGetSuccessResponse:
    type: array
    items:
      type: object
      properties:
        account:
          type: string
        datas: 
          type: array
          items:
            properties:
              id: 
                type: string
              date:
                type: string
              description:
                type: string
              amount:
                type: number
              balance:
                type: number
  UpdateTransaction:
      type: object
      properties:
        category:
          type: string
        notes:
          type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string