openapi: 3.0.3
info:
  title: Argent Bank
  description: Voici une  description des endpoints nécessaires à l'API banquaire 'Argent Bank'. Elle décrit plus précisément comment récupérer les transactions et les informations qui y sont liés.
  contact:
    email: fofana_bintou@outlook.fr
  termsOfService: https://smartbear.com/terms-of-use/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:3001/api/v1/user/bank
tags:
  - name: Transactions
    description: Transaction d'épargne
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /transaction:
    put:
      tags:
        - Transactions
      summary: Met à jour les infos sur les transactions d'épargne
      description: Met à jour les transactions d'épargne
      operationId: updateSaving
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token - Permet de s'assurer que le client détient les droits nécessaires
          required: true
          schema:
            type: string
        - name: body
          in: query
          description: Met à jour une transaction d'épargne, les propriétés renseignées seront mises à jour
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateTransaction'
              
      responses:
        '200':
          description: Requête réussie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '401':
          description: Utilisateur non authorisé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailedResponse'
        '404':
          description: Id de transaction invalide
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailedResponse'
      security:
        - Bearer: []
    post:
      tags:
        - Transactions
      summary: Ajoute une transaction d'épargne
      description: Ajoute une transaction d'épargne
      operationId: addSaving
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token - Permet de s'assurer que le client détient les droits nécessaires
          required: true
          schema:
            type: string
            example: 'Bearer Auth_key'
        - name: body
          in: query
          description: Ajoute une transaction d'épargne, les propriétés renseignées seront mises à jour
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostTransaction'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: Paramètres invalide
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailedResponse'
        '401':
          description: Utilisateur non authorisé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailedResponse'
      security:
        - Bearer: []
    get:
      tags:
        - Transactions
      summary: Récupère toutes les transactions d'épargne
      description: Récupère toutes les transactions d'épargne
      operationId: getSavings
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token - Permet de s'assurer que le client détient les droits nécessaires
          required: true
          schema:
            type: string
            example: 'Bearer Auth_key'
        - name: body
          in: query
          description: Spécifier le type afin de récupérer toutes les transactions de ce type
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTransactions'
      responses:
        '200' :
          description: Succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '401':
          description: Utilisateur non authorisé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailedResponse'
      security:
        - Bearer: []
  /transaction/{transaction_id}:
    get:
      tags:
        - Transactions
      summary: Récupère une transaction d'épargne spécifique
      description: Récupère une transaction d'épargne spécifique
      operationId: getSaving
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token - Permet de s'assurer que le client détient les droits nécessaires
          required: true
          schema:
            type: string
            example: 'Bearer Auth_key'
        - name: transaction_id
          in: path
          description: Récupère une transaction spécifique
          required: true
          schema: 
            type: string
      responses:
        '200' :
          description: Succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '401':
          description: Utilisateur non authorisé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailedResponse'
      security:
        - Bearer: []
components:
  schemas:
    transaction:
      type: object
      properties:
        id: 
          type: integer
        date:
          type: string
        category:
          type: string
        transactionType: 
          type: string
        notes:
          type: string
        montant:
          type: number
    UpdateTransaction:
      type: object
      properties:
        id: 
          type: integer
        properties: 
          type: object
          properties:
            category:
              type: string
            transactionType:
              type: string
            notes:
              type: string
            montant:
              type: number
    GetTransactions:
      type: object
      properties:
        type: 
          type: string
    PostTransaction:
      type: object
      properties:
        id: 
          type: integer
        type:
          type: string
        date:
          type: string
        category:
          type: string
        transactionType:
          type: string
        notes:
          type: string
    SuccessResponse:
      type: object
      properties:
        status:
          type: integer
          example: 200
        body:
          type: array
          items:
            $ref: '#/components/schemas/transaction'
    FailedResponse:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
  securitySchemes:
    Bearer:
      type: apiKey
      in: header
      name: Authorization
      
        